<?php

declare(strict_types=1);

namespace App\Adapter\Api\Middleware;

use App\Infrastructure\Api\Request\InputInterface;
use App\Infrastructure\Api\Request\Parser\InputParserInterface;
use App\Infrastructure\Api\Request\Validation\InputValidatorInterface;
use App\Infrastructure\Api\Response\ApiThrowableResponseFactoryInterface as ResponseFactory;
use Override;
use Psr\Http\Message\ResponseInterface;
use Psr\Http\Message\ServerRequestInterface;
use Psr\Http\Server\MiddlewareInterface;
use Psr\Http\Server\RequestHandlerInterface;
use Throwable;

/**
 * Middleware to bind and validate input data into a specified DTO class.
 *
 * This middleware extracts the 'id' attribute from the request,
 * parses the query parameters and body content, validates the resulting DTO,
 * and injects it back into the request for further handling.
 */
final readonly class ValidatedInputMiddleware implements MiddlewareInterface
{
    /**
     * Constructor for ValidatedInputMiddleware.
     *
     * @param class-string<InputInterface> $dtoClass The fully qualified class name of the DTO to bind and validate.
     * @param InputParserInterface $inputParser The input parser to parse request data.
     * @param InputValidatorInterface $inputValidator The input validator to validate the parsed DTO.
     * @param ResponseFactory $responseFactory Factory to create error responses in case of exceptions.
     */
    public function __construct(
        private string $dtoClass,
        private InputParserInterface $inputParser,
        private InputValidatorInterface $inputValidator,
        private ResponseFactory $responseFactory,
    ) {
    }

    /**
     * Process an incoming server request and return a response.
     *
     * This method extracts the 'id' attribute from the request, parses the query parameters
     * and body content, validates the resulting DTO, and injects it back into the request
     * for further handling.
     *
     * @param ServerRequestInterface $request The incoming server request.
     * @param RequestHandlerInterface $handler The request handler to process the request.
     * @return ResponseInterface The response generated by the request handler.
     * @throws Throwable If an error occurs during parsing or validation.
     */
    #[Override]
    public function process(ServerRequestInterface $request, RequestHandlerInterface $handler): ResponseInterface
    {
        $attributeId = $request->getAttribute('id');
        $parsedBody = (array)($request->getParsedBody() ?? []);

        try {
            $this->inputParser->parse($attributeId, $parsedBody);
            $dto = new ($this->dtoClass)($this->inputParser->getData());
            $this->inputValidator->validate($dto);
        } catch (Throwable $exception) {
            return $this->responseFactory->createResponse($exception);
        }

        // Injects the DTO into the request, indexed by the fully qualified class name
        $request = $request->withAttribute($this->dtoClass, $dto);

        return $handler->handle($request);
    }
}
