name-template: 'v$RESOLVED_VERSION ðŸš€'
tag-template: 'v$RESOLVED_VERSION'
template: |
  ## What changed

  Comparison with the previous version: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION

  $CHANGES

change-template: '* $TITLE (#$NUMBER) @$AUTHOR'
change-title-escapes: '\<*_&'
filter-by-commitish: true
commitish: 'refs/heads/main'
exclude-labels:
  - 'skip-changelog'

categories:

  - title: 'â­ï¸ Added'
    labels:
      - 'âœ¨ feature'

  - title: 'ðŸ›  Changed'
    labels:
      - 'ðŸ›  changed'

  - title: 'ðŸ’€ Deprecated'
    labels:
      - 'ðŸ’€ deprecated'

  - title: 'ðŸ—‘ Removed'
    labels:
      - 'ðŸ—‘ removed'

  - title: 'ðŸ› Fixed'
    labels:
      - 'ðŸ› fixed'

  - title: 'ðŸ”’ Security implemented'
    labels:
      - 'ðŸ”’ security'

  - title: 'ðŸ¤ðŸ½ Modified dependency'
    labels:
      - 'ðŸ¤ dependency'

  - title: 'ðŸš¨ Breaking changed'
    labels:
      - 'ðŸš¨ breaking'

version-resolver:

  major:
    labels:
      - 'âš ï¸ major'
      - 'ðŸš¨ breaking'

  minor:
    labels:
      - 'ðŸ§© minor'
      - 'âœ¨ feature'

  patch:
    labels:
      - 'ðŸ”§ patch'
      - 'ðŸ›  changed'
      - 'ðŸ’€ deprecated'
      - 'ðŸ—‘ removed'
      - 'ðŸ› fixed'
      - 'ðŸ”’ security'
      - 'ðŸ¤ dependency'

  default: patch

replacers:

  - search: '/build\([0-9a-z]{1,}\): /'
    replace: ''

  - search: 'build: '
    replace: ''

  - search: '/chore\([0-9a-z]{1,}\): /'
    replace: ''

  - search: 'chore: '
    replace: ''

  - search: '/ci\([0-9a-z]{1,}\): /'
    replace: ''

  - search: 'ci: '
    replace: ''

  - search: '/docs\([0-9a-z]{1,}\): /'
    replace: ''

  - search: 'docs: '
    replace: ''

  - search: '/feat\([0-9a-z]{1,}\): /'
    replace: ''

  - search: 'feat: '
    replace: ''

  - search: '/fix\([0-9a-z]{1,}\): /'
    replace: ''

  - search: 'fix: '
    replace: ''

  - search: '/perf\([0-9a-z]{1,}\): /'
    replace: ''

  - search: 'perf: '
    replace: ''

  - search: '/refactor\([0-9a-z]{1,}\): /'
    replace: ''

  - search: 'refactor: '
    replace: ''

  - search: '/revert\([0-9a-z]{1,}\): /'
    replace: ''

  - search: 'revert: '
    replace: ''

  - search: '/style\([0-9a-z]{1,}\): /'
    replace: ''

  - search: 'style: '
    replace: ''

  - search: '/test\([0-9a-z]{1,}\): /'
    replace: ''

  - search: 'test: '
    replace: ''
