<?php

declare(strict_types=1);

namespace App\Infrastructure\Api\Handler;

use App\Infrastructure\Api\Response\ApiThrowableResponseFactoryInterface;
use Override;
use Psr\Http\Message\ResponseInterface;
use Psr\Http\Message\ServerRequestInterface;
use Psr\Http\Server\RequestHandlerInterface;
use Throwable;

/**
 * Class RequestHandlerDecorator
 *
 * A decorator for request handlers that catches exceptions and converts them
 * into HTTP responses using a throwable response factory.
 *
 * This class implements the RequestHandlerInterface and provides a way to
 * handle requests while ensuring that any exceptions thrown during processing
 * are gracefully converted into appropriate HTTP responses.
 */
final readonly class RequestHandlerDecorator implements RequestHandlerInterface
{
    /**
     * Initializes the decorator with a request handler and a throwable handler.
     *
     * @param RequestHandlerInterface $innerHandler The request handler to be decorated.
     * @param ApiThrowableResponseFactoryInterface $throwableResponseFactory Convert exceptions into HTTP responses.
     */
    public function __construct(
        private RequestHandlerInterface $innerHandler,
        private ApiThrowableResponseFactoryInterface $throwableResponseFactory,
    ) {
    }

    /**
     * Handles the incoming request by delegating to the inner handler and
     * catching any exceptions that occur during processing.
     *
     * @param ServerRequestInterface $request The incoming request to handle.
     *
     * @return ResponseInterface The response generated by the request handler.
     */
    #[Override]
    public function handle(ServerRequestInterface $request): ResponseInterface
    {
        try {
            $response = $this->innerHandler->handle($request);
        } catch (Throwable $exception) {
            $response = $this->throwableResponseFactory->createResponse($exception);
        }

        return $response;
    }
}
